### ISSUE TITLE
Can't write in mobile browser

### ISSUE THREAD

**Issue by Lizirui** [MyScript/web-integration-samples#2]
I copied the demo of vue. I can't write it on my mobile browser after launching, but I can open the demo of the official website with my mobile browser. Please tell me how to solve this problem, thank you very much.

**Comment by Lizirui** [comment]
Can't write, it means that the finger slides on the mobile browser and there is no reaction.

**Comment by padewitte** [comment]
Sorry for the delay

In this code example the Pointer Event Polyfill (Pep) was not load and the touch-action=none attribute was not set to the DOM element containing the editor. Those element are mandatory for Safari and iOS devices. The code has just been updated to fix that. Please make a fresh pull and start again this shoudl be better.

Please have a look to the [commit](https://github.com/MyScript/web-integration-samples/commit/d747fc2b69b666ed4f40ac009b95f05ff33b403a) for more insigth

**Comment by Lizirui** [comment]
@padewitte 
Thank you very much for your answer and solved my problem.
