### ISSUE TITLE
react MATH  component problem

### ISSUE THREAD

**Issue by leenty** [MyScript/web-integration-samples#3]
I set the "MATH" type at react demo, 
And the request `wss://webdemoapi.myscript.com/api/v4.0/iink/document` has responded,But not shown on the view.
How can I show it.

```
{
  "type": "exported",
  "partId": "jxbtxgpj",
  "exports": {
    "application/x-latex": "\\sqrt {3}",
    "application/mathml+xml": "<math xmlns='http://www.w3.org/1998/Math/MathML'>\n  <msqrt>\n    <mn> 3 </mn>\n  </msqrt>\n</math>\n"
  }
}
```

**Comment by MyScriptSupport** [comment]
Dear Leenty,

Thank you for contacting us.
In order to help you, could you please, give us more details about what you mean by you can't show:
do you mean there is nothing displayed at all in your browser when you are writing ?

Regards,

MyScript Support.

**Comment by leenty** [comment]
I run react-integration-examples. 
Then modified the type value to "MATH", And the value has been returned.
But the latex and svg results are not displayed on the interface.
How to show latex and svg?
I want a full "MATH" type of react demo like web-samples.
In fact, I need a myscript npm package api document, I want to use it to do some custom content.

thanks help🙏🙏🙏

![image](https://user-images.githubusercontent.com/13213680/53803598-26c02080-3f80-11e9-90b7-f4ccfe1d753e.png)

![image](https://user-images.githubusercontent.com/13213680/53803287-34c17180-3f7f-11e9-8428-54e709b05bfc.png)

**Comment by MyScriptSupport** [comment]
Dear Leenty,

First of all, you should not let the image with your hmac and application Keys on GitHub, as anybody could you use them.

The API documentation is available at [https://myscript.github.io/MyScriptJS/docs/](url).

As far as we understand, you would like to perform a Latex export. You may take a look at the following example [https://github.com/MyScript/MyScriptJS/blob/master/examples/v4/websocket_math_iink.html](url) to build your application.

Regards,

MyScriptSupport

**Comment by leenty** [comment]
Thank you for your support, my problem has been solved.
The application key is from the example of the myscript npm package.
I have applied for a application Key and replaced it.

**Comment by jp9573** [comment]
Hey, I'm having a similar problem while exploring integration for React. Can you please share what exact changes do I have to perform in order to get the export for math component.

Thanks in advance.

**Comment by MyScriptSupport** [comment]
Dear Jay,

thank you for contacting us. For faster answers, we recommend you submit any question you may have on our developer forum: https://developer-support.myscript.com/support/discussions

Currently, it looks like you have an issue  with your application  or hmac key ; you shall then proceed as indicated in the following topic: https://developer-support.myscript.com/support/discussions/topics/16000028796

Best regards,

Olivier
